# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e89f53a124b2f49fef4df3afac871a208a0c00681ddeee4767ac16579001352e667941315045c59a250fbdf659a66534ca5a4bee926eb5a452edf6164d45b9

test:
  secret_key_base: 3aa637b03b060f942c9bfea8ba391bc4853dfa763e8c3059b15ff02d67a5b3fcc6829dd2fc9f9c9025a9a4de4fc43f27f2ed59154ea8803d075a00f69972a9d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
